### ISSUE TITLE
Create the workflows page.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/project-odin#24]
### 🔢 Version

🐣 Pre-Release

### 🤔 What problem does your proposition aim to solve?

Project Odin will allow end users to define custom workflows. As a result, we need a page where they can:

- Choose to run an existing workflow.
- Create a new workflow.
- See scheduled workflows.

### 📝 How would you like the feature to work?

We want to draw inspiration from [this Dribbble shot](https://dribbble.com/shots/19737969-Ninox-Admin-Dashboard-Analytics-UX):

![image](https://user-images.githubusercontent.com/65432314/222735738-1b8221ca-0b14-4dd7-8cc8-27b537a2ad30.png)

Implementing this type of design will require a few elements:

- [x] #25 
- [x] #26 
- [x] #27 
- [x] #28 

Due to the scale of this issue, we will be creating individual work items to tackle the aforementioned tasks in chunks.

### 🧪 What have you already tried?

Not applicable.

**Comment by SophiaPerzan** [comment]
Is there anything else that needs to be done before this can be closed?

**Comment by tacosontitan** [comment]
@SophiaPerzan there is not, thank you for the reminder. I've been slammed with work recently so I haven't been able to get in and update issues and create new ones. There's still plenty of UI work to be done, but I have to get some time to work my way through things mentally, though I can create a discussion thread if you're interested in collaborating on that front too! :)
