### ISSUE TITLE
Create a component for command interactions on the workflows page.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/project-odin#27]
### 🔢 Version

🐣 Pre-Release

### 🤔 What problem does your proposition aim to solve?

Project Odin will allow end users to define custom workflows. As a result, we need a page where they can:

- Choose to run an existing workflow.
- Create a new workflow.
- See scheduled workflows.

### 📝 How would you like the feature to work?

We want to draw inspiration from [this Dribbble shot](https://dribbble.com/shots/19737969-Ninox-Admin-Dashboard-Analytics-UX):

![image](https://user-images.githubusercontent.com/65432314/222735738-1b8221ca-0b14-4dd7-8cc8-27b537a2ad30.png)

The workflows page needs a component that allows users to invoke commands like creating a new workflow. The baseline requirements are:

- [x] Create a component for displaying each command in a tile.
- [x] Create two initial command signatures for the component to consume:
  - [x] Create a new workflow.
  - [x] Schedule a workflow invocation.

#### 🎨 What are some design points we're considering for this?

- The component should display commands in a single row.
- The component should allow overflow on the x-axis, not the y-axis.
- The component should stick to the bottom of the page.

### 🧪 What have you already tried?

Not applicable.

**Comment by SophiaPerzan** [comment]
A quick question:
"Create a data model that represents commands" - This is just adding some extra functions in WorflowService to manage the workflows, right?

**Comment by tacosontitan** [comment]
> A quick question: "Create a data model that represents commands" - This is just adding some extra functions in WorflowService to manage the workflows, right?

Actually, we can abandon that particular step. The idea behind it was to have a data model that represents each action available for execution, but I don't think it's needed at this point.
