### ISSUE TITLE
Create a component for rendering the upcoming workflow schedule.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/project-odin#28]
### 🔢 Version

🐣 Pre-Release

### 🤔 What problem does your proposition aim to solve?

Project Odin will allow end users to define custom workflows. As a result, we need a page where they can:

- Choose to run an existing workflow.
- Create a new workflow.
- See scheduled workflows.

### 📝 How would you like the feature to work?

We want to draw inspiration from [this Dribbble shot](https://dribbble.com/shots/19737969-Ninox-Admin-Dashboard-Analytics-UX):

![image](https://user-images.githubusercontent.com/65432314/222735738-1b8221ca-0b14-4dd7-8cc8-27b537a2ad30.png)

This component should display all of the upcoming scheduled workflows in a row with overflow on the x-axis. Each tile should display the following information:

- Workflow Icon (small and to the left)
- Workflow Name
- Scheduled Date and Time

The baseline deliverables for this feature are:

- [x] Create a data model for representing a scheduled workflow.
- [x] Create a component for rendering a scheduled workflow tile.
- [x] Create a component for rendering all upcoming scheduled workflows.

From a design perspective, the component should stick to the bottom of the workflows page.

### 🧪 What have you already tried?

Not applicable.

**Comment by SophiaPerzan** [comment]
So for the scheduled workflow component, would it looks something like this?

<table>
<thead>
<tr>
<th>🔂 Workflow name</th>
</thead>
<tbody>
<tr>
<td>Scheduled time: 8h 30m from now</td>
</tr>
</tbody>
</table>

**Comment by SophiaPerzan** [comment]
Also is this component supposed to be below the command components? Or above?

**Comment by tacosontitan** [comment]
I'm thinking something like this, from the screenshot above:

![image](https://user-images.githubusercontent.com/65432314/224506479-700e4116-2d22-415b-9646-850f0184b612.png)

Which is close to your proposed table, as for the above or below, below. 😄

**Comment by SophiaPerzan** [comment]
Oh woops, completely missed that in the screenshot. I'll get right on it!

**Comment by SophiaPerzan** [comment]
Ok, I'm basically almost done but I was hoping I could get some clarification on the overflows. 

My current understanding is all of the elements should be displayed in separate groups. These groups should take up a single row if possible, otherwise they would 'overflow' onto as many additional lines they need to all be rendered. And if there are too many elements to fit on the page (currently they just get cut off), there should be a vertical scroll bar so you can scroll down to see the other elements. Is this correct?

**Comment by tacosontitan** [comment]
There should be three sections to the layout of the workflows page:

- Workflows Area
- Workflow Commands Area
- Scheduled Workflows Area

The workflows area should overflow vertically while the commands and scheduled workflows areas should overflow horizontally. This way, if any of the three areas has too many elements to render in the visible screen space, a scroll bar becomes available which allows consumers to scroll through the available information.

Does that help?

**Comment by SophiaPerzan** [comment]
Yes, that explains things well. If the workflows area gets too large, a vertical scroll bar should appear as well, right?

**Comment by tacosontitan** [comment]
That is correct :)
